<?php
defined( 'ABSPATH' ) || exit;

Redux::set_section( // General colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'General colors', 'bijan' ),
		'id'			=> 'colors-general-section',
		'subsection'	=> true,
		'fields'		=> array(
			[
				'id'			=> 'body_color',
				'type'			=> 'color',
				'title'			=> __( 'Body color', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#ffffff' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#ffffff',
			],
			[
				'id'			=> 'text_main_color',
				'type'			=> 'color',
				'title'			=> __( 'Default text color', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#9B9CA4' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#9B9CA4',
			],
		),
	)
);

Redux::set_section( // Primary colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'Primary colors', 'bijan' ),
		'id'			=> 'colors-primary-section',
		'subsection'	=> true,
		'fields'		=> array(
			[
				'id'			=> 'primary_color_100',
				'type'			=> 'color',
				'title'			=> __( 'Primary', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#FF9800' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#FF9800',
			],
			[
				'id'			=> 'primary_color_200',
				'type'			=> 'color',
				'title'			=> __( 'Primary 2', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#FFB74D' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#FFB74D',
			],
			[
				'id'			=> 'primary_color_300',
				'type'			=> 'color',
				'title'			=> __( 'Primary 3', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#FFCB80' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#FFCB80',
			],
			[
				'id'			=> 'primary_color_400',
				'type'			=> 'color',
				'title'			=> __( 'Primary 4', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#FFE0B3' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#FFE0B3',
			],
			[
				'id'			=> 'primary_color_500',
				'type'			=> 'color',
				'title'			=> __( 'Primary 5', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#FFF5E5' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#FFF5E5',
			],
			[
				'id'			=> 'primary_color_hover',
				'type'			=> 'color',
				'title'			=> __( 'Primary hover', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#EB8C00' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#EB8C00',
			],
		),
	)
);

Redux::set_section( // Secondary colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'Secondary colors', 'bijan' ),
		'id'			=> 'colors-secondary-section',
		'subsection'	=> true,
		'fields'		=> array(
			[
				'id'			=> 'secondary_color_100',
				'type'			=> 'color',
				'title'			=> __( 'Secondary', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#2C7865' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#2C7865',
			],
			[
				'id'			=> 'secondary_color_200',
				'type'			=> 'color',
				'title'			=> __( 'Secondary 2', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#4D9784' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#4D9784',
			],
			[
				'id'			=> 'secondary_color_300',
				'type'			=> 'color',
				'title'			=> __( 'Secondary 3', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#6CB7A4' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#6CB7A4',
			],
			[
				'id'			=> 'secondary_color_400',
				'type'			=> 'color',
				'title'			=> __( 'Secondary 4', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#9DDACB' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#9DDACB',
			],
			[
				'id'			=> 'secondary_color_500',
				'type'			=> 'color',
				'title'			=> __( 'Secondary 5', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#D9F3ED' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#D9F3ED',
			],
			[
				'id'			=> 'secondary_color_hover',
				'type'			=> 'color',
				'title'			=> __( 'Secondary hover', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#225D4F' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#225D4F',
			],
		),
	)
);

Redux::set_section( // Tertiary colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'Tertiary colors', 'bijan' ),
		'id'			=> 'colors-tertiary-section',
		'subsection'	=> true,
		'fields'		=> array(
			[
				'id'			=> 'tertiary_color_100',
				'type'			=> 'color',
				'title'			=> __( 'Tertiary', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#90D26D' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#90D26D',
			],
			[
				'id'			=> 'tertiary_color_200',
				'type'			=> 'color',
				'title'			=> __( 'Tertiary 2', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#B1DF99' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#B1DF99',
			],
			[
				'id'			=> 'tertiary_color_300',
				'type'			=> 'color',
				'title'			=> __( 'Tertiary 3', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#C7E8B6' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#C7E8B6',
			],
			[
				'id'			=> 'tertiary_color_400',
				'type'			=> 'color',
				'title'			=> __( 'Tertiary 4', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#DEF2D3' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#DEF2D3',
			],
			[
				'id'			=> 'tertiary_color_500',
				'type'			=> 'color',
				'title'			=> __( 'Tertiary 5', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#F4FBF0' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#F4FBF0',
			],
		),
	)
);

Redux::set_section( // Gray colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'Gray colors', 'bijan' ),
		'id'			=> 'colors-gray-section',
		'subsection'	=> true,
		'fields'		=> array(
			[ // gray_color_100
				'id'			=> 'gray_color_100',
				'type'			=> 'color',
				'title'			=> __( 'Gray 1', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#353535' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#353535',
			],
			[ // gray_color_200
				'id'			=> 'gray_color_200',
				'type'			=> 'color',
				'title'			=> __( 'Gray 2', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#5F5F5F' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#5F5F5F',
			],
			[ // gray_color_300
				'id'			=> 'gray_color_300',
				'type'			=> 'color', 
				'title'			=> __( 'Gray 3', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#888888' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#888888',
			],
			[ // gray_color_400
				'id'			=> 'gray_color_400',
				'type'			=> 'color',
				'title'			=> __( 'Gray 4', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#ADADAD' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#ADADAD',
			],
			[ // gray_color_500
				'id'			=> 'gray_color_500',
				'type'			=> 'color',
				'title'			=> __( 'Gray 5', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#CFCFCF' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#CFCFCF',
			],
			[ // gray_color_600
				'id'			=> 'gray_color_600',
				'type'			=> 'color',
				'title'			=> __( 'Gray 6', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#F0F0F0' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#F0F0F0',
			],
			[
				'id'			=> 'gray_color_700',
				'type'			=> 'color',
				'title'			=> __( 'Gray 7', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#7E8089' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#7E8089',
			],
		),
	)
);

Redux::set_section( // Text colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'Text colors', 'bijan' ),
		'id'			=> 'colors-text-section',
		'subsection'	=> true,
		'fields'		=> array(
			[
				'id'			=> 'text_color_100',
				'type'			=> 'color',
				'title'			=> __( 'Text 1', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#2e313c' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#2e313c',
			],
			[
				'id'			=> 'text_color_200',
				'type'			=> 'color',
				'title'			=> __( 'Text 2', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#4e5364' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#4e5364',
			],
			[
				'id'			=> 'text_color_300',
				'type'			=> 'color',
				'title'			=> __( 'Text 3', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#7e8089' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#7e8089',
			],
			[
				'id'			=> 'text_color_400',
				'type'			=> 'color',
				'title'			=> __( 'Text 4', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#9b9ca4' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#9b9ca4',
			],
			[
				'id'			=> 'text_color_500',
				'type'			=> 'color',
				'title'			=> __( 'Text 5', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#cfcfcf' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#cfcfcf',
			],
			[
				'id'			=> 'text_color_600',
				'type'			=> 'color',
				'title'			=> __( 'Text 6', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#F0F0F0' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#F0F0F0',
			],
		),
	)
);

Redux::set_section( // Form colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'Form colors', 'bijan' ),
		'id'			=> 'colors-form-section',
		'subsection'	=> true,
		'fields'		=> array(
			[
				'id'			=> 'input_bg',
				'type'			=> 'color',
				'title'			=> __( 'Input background', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#F0F0F0' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#F0F0F0',
			],
			[
				'id'			=> 'input_text',
				'type'			=> 'color',
				'title'			=> __( 'Input text color', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#9B9CA4' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#9B9CA4',
			],
		),
	)
);

Redux::set_section( // Widget colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'Widget colors', 'bijan' ),
		'id'			=> 'colors-widget-section',
		'subsection'	=> true,
		'fields'		=> array(
			[
				'id'			=> 'widget_bg',
				'type'			=> 'color',
				'title'			=> __( 'Widget background', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#ffffff' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#ffffff',
			],
			[
				'id'			=> 'widget_title_bg',
				'type'			=> 'color',
				'title'			=> __( 'Widget title background color', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#F0F0F0' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#F0F0F0',
			],
			[
				'id'			=> 'widget_title',
				'type'			=> 'color',
				'title'			=> __( 'Widget title color', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#4E5364' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#4E5364',
			],
			[
				'id'			=> 'widget_text_color',
				'type'			=> 'color',
				'title'			=> __( 'Widget text color', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#9B9CA4' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#9B9CA4',
			],
			[
				'id'			=> 'widget_links_color',
				'type'			=> 'color',
				'title'			=> __( 'Widget links color', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#FF9800' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#FF9800',
			],
		),
	)
);

Redux::set_section( // Scrollbar colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'Scrollbar colors', 'bijan' ),
		'id'			=> 'colors-scrollbar-section',
		'subsection'	=> true,
		'fields'		=> array(
			[
				'id'			=> 'scrollbar-normal-color',
				'type'			=> 'color',
				'title'			=> __( 'Scrollbar normal color', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#FFB74D' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#FFB74D',
			],
			[
				'id'			=> 'scrollbar-hover-color',
				'type'			=> 'color',
				'title'			=> __( 'Scrollbar hover color', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#FF9800' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#FF9800',
			],
			[
				'id'			=> 'scrollbar-bg',
				'type'			=> 'color',
				'title'			=> __( 'Scrollbar background color', 'bijan' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'bijan' ), '#F0F0F0' ),
				'compiler'		=> true,
				'validate'		=> 'color',
				'transparent'	=> false,
				'default'		=> '#F0F0F0',
			],
		),
	)
);